sudo: required
language: php
dist: trusty
php:
- 7.2
services:
- mysql
before_script:
- cp .env.travis .env
- mysql -e 'create database medicli_tests;'
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate --seed
script:
- vendor/bin/phpunit
notifications:
  email:
    recipients:
    - felipe-guzman.c@hotmail.com
    on-success: always
    on-failure: always
deploy:
  provider: heroku
  api_key:
    secure: HKoOPKoCiAhYOwKT1ncAsBTo0nvFQxI/H/BSuJQ3UfEZYhtyxRAGGyX//8m+c4IRCdNYvMJ/aAXwLX9vrHB1A0pQMLgT0L6lzI9da5JoGc9dJwFMaPkyRZUfcfrYhkMLhBxuUvnyNRaFCTWd/Ev6La9GGyOp0R7bjnlqnonhplmzZrxAEK5IpX6TotdsGGrjtOoXccYTIFSMvf4REwxOpo0ossp0CTc6uITiJxsF9x+jpRNfHv/g1WK4TtrY85w5do8Ih9eKngyOB3uOzM6hC3/6O/AJB4/ZCPDdlZqJSYjnAwzao+cKxMTsOeAJPYk3y3O0hMSpim6NOop91+XXRgzBKSv3gUvTjT/npDnFujvOLvuRlCYLtJm/RBT1W0/tu5s8Q3XUXoa5sYbQh8QK+F4a9Y3J4krdIEbgGIJVML+hrGD8dblmbPaG6JK8Z680FxyH/TSkQ6ZlR/fhWY4D3c30gCxqXb+vmZuVLTkyOFBFCwGBAgY0TFBeS+00pLbj2JG6W3///U9LltkDtm4Nt9ePQYgaKDAgF80jC4uPV/322hF+nGeBHFa81XUChVyrDAaL36LJ6Z6tnkAFKT3NE+6ReYg0SUQXLqKc3Jk0BskJyRcte1phwssKX++7VrxOxOzqT2amhEqkuf6QghW9sh84WwMRs+gQf/RD2Idta3k=
  app: medicli
  on: master
  run:
    - "heroku run php artisan migrate"
    - "heroku run php artisan db:seed"
    - "heroku run npm run production"
